/** @vitest-environment jsdom */
import { describe, expect, it } from 'vitest';
import userEvent, { type UserEvent } from '@testing-library/user-event';
import { screen } from '@testing-library/react';
import { fakeBrowser } from 'wxt/testing/fake-browser';
import { fakeApi, type FakeApi } from '../../../testing/fakeApi';
import { openPanel, stubScreenshot } from '../../../testing/panel';
import { closeEditorWindows } from '../../../testing/editorWindows';
import matchNone from '../../../testing/fixtures/match-none.json';
import upload from '../../../testing/fixtures/upload.json';

/** The form that carries a page address, so the screenshot list can guard the site. */
async function openReportService(user: UserEvent, pageUrl: string): Promise<FakeApi> {
  const api = fakeApi()
    .on('POST', '/services/match', { data: matchNone })
    .on('POST', '/uploads/evidence', { json: upload })
    .on('POST', '/submissions', { status: 201, json: { id: 'receipt' } })
    .install();
  await openPanel(pageUrl);
  await user.click(await screen.findByRole('button', { name: 'Report a Service' }, { timeout: 3000 }));
  await screen.findByRole('heading', { name: 'Report a Service' });
  return api;
}

// Screenshots come from generated bytes, never a real capture (spec 0001, AC-4).
describe('the screenshot list', () => {
  it('lists a screenshot and drops it when it is removed (covers AC-4)', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    await openReportService(user, 'https://shots.example/download');

    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByAltText('Evidence #1');
    expect(screen.getByRole('button', { name: 'Add another screenshot' })).toBeDefined();

    await user.click(screen.getByRole('button', { name: 'Remove evidence #1' }));
    expect(screen.queryByAltText('Evidence #1')).toBeNull();
    expect(screen.getByRole('button', { name: 'Add screenshot' })).toBeDefined();
  });

  it('uploads once and reuses that upload when a send is refused (covers AC-4)', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    let sends = 0;
    const api = fakeApi()
      .on('POST', '/services/match', { data: matchNone })
      .on('POST', '/uploads/evidence', { json: upload })
      .on('POST', '/submissions', () => {
        sends += 1;
        return sends === 1
          ? { status: 422, json: { error: 'INVALID', message: 'Needs a description' } }
          : { status: 201, json: { id: 'receipt' } };
      })
      .install();
    await openPanel('https://retry.example/download');
    await user.click(await screen.findByRole('button', { name: 'Report a Service' }, { timeout: 3000 }));
    await screen.findByRole('heading', { name: 'Report a Service' });

    await user.type(screen.getByRole('textbox', { name: 'Service name' }), 'Blocked Service');
    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByAltText('Evidence #1');
    // The capture opened the editor; the tester closes it without changes.
    await closeEditorWindows();

    await user.click(screen.getByRole('button', { name: 'Submit Report' }));
    await screen.findByText('Needs a description');
    expect(api.callsTo('POST', '/uploads/evidence')).toHaveLength(1);
    expect(api.callsTo('POST', '/submissions')).toHaveLength(1);

    await user.click(screen.getByRole('button', { name: 'Submit Report' }));
    await screen.findByRole('heading', { name: 'Report received' });
    expect(api.callsTo('POST', '/uploads/evidence')).toHaveLength(1);
    expect(api.callsTo('POST', '/submissions').at(1)?.json).toMatchObject({
      evidenceUrls: [upload.file.url],
    });
  });

  it('shows an upload that answers without a file address, and can be sent again', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    let uploads = 0;
    const api = fakeApi()
      .on('POST', '/services/match', { data: matchNone })
      .on('POST', '/uploads/evidence', () => {
        uploads += 1;
        return uploads === 1 ? { json: null } : { json: upload };
      })
      .on('POST', '/submissions', { status: 201, json: { id: 'receipt' } })
      .install();
    await openPanel('https://empty-upload.example/download');
    await user.click(await screen.findByRole('button', { name: 'Report a Service' }, { timeout: 3000 }));
    await screen.findByRole('heading', { name: 'Report a Service' });
    await user.type(screen.getByRole('textbox', { name: 'Service name' }), 'Blocked Service');
    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByAltText('Evidence #1');
    // The capture opened the editor; the tester closes it without changes.
    await closeEditorWindows();

    await user.click(screen.getByRole('button', { name: 'Submit Report' }));
    expect((await screen.findByRole('alert')).textContent).toBe(
      'A screenshot could not be uploaded: The upload answered without a file address.',
    );
    // Not stuck sending: the form can be sent again, and nothing was submitted.
    const send = screen.getByRole<HTMLButtonElement>('button', { name: 'Submit Report' });
    expect(send.disabled).toBe(false);
    expect(api.callsTo('POST', '/submissions')).toHaveLength(0);

    await user.click(send);
    await screen.findByRole('heading', { name: 'Report received' });
    expect(api.callsTo('POST', '/uploads/evidence')).toHaveLength(2);
    expect(api.callsTo('POST', '/submissions').at(0)?.json).toMatchObject({ evidenceUrls: [upload.file.url] });
  });

  it('holds back a screenshot taken on another site until it is pressed again (covers AC-4)', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    await openReportService(user, 'https://forms.example/download');

    // The tester switches tabs, which is how a capture lands on the wrong site.
    await Promise.resolve(fakeBrowser.tabs.create({ url: 'https://elsewhere.example/report', active: true }));
    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByText(/This tab shows elsewhere\.example, not forms\.example/);
    expect(screen.queryByAltText('Evidence #1')).toBeNull();

    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByAltText('Evidence #1');
  });
});
