/** @vitest-environment jsdom */
import { describe, expect, it, vi } from 'vitest';
import userEvent, { type UserEvent } from '@testing-library/user-event';
import { act, fireEvent, render, renderHook, screen, waitFor } from '@testing-library/react';
import { FormShell, emailError, useSavedEmail, useScreenshotLists } from './FormParts';
import { saveEmail } from '../../../lib/settings';
import type { PendingEvidence } from '../../../lib/evidence';
import { fakeBrowser } from 'wxt/testing/fake-browser';
import { fakeApi, type FakeApi } from '../../../testing/fakeApi';
import { openPanel, stubScreenshot } from '../../../testing/panel';
import { closeEditorWindows } from '../../../testing/editorWindows';
import matchNone from '../../../testing/fixtures/match-none.json';
import upload from '../../../testing/fixtures/upload.json';

it('still protects unsent form drafts on Back and unload', async () => {
  const user = userEvent.setup();
  const onBack = vi.fn();
  render(
    <FormShell backLabel="Back" onBack={onBack} title="Report" intro="Describe the issue.">
      <input aria-label="Description" />
    </FormShell>,
  );
  await user.type(screen.getByRole('textbox', { name: 'Description' }), 'Unsent report');
  const unload = new Event('beforeunload', { cancelable: true });
  window.dispatchEvent(unload);
  expect(unload.defaultPrevented).toBe(true);
  await user.click(screen.getByRole('button', { name: 'Back' }));
  expect(onBack).not.toHaveBeenCalled();
  expect(screen.getByRole('dialog', { name: 'Discard this draft?' })).toBeDefined();
  await user.click(screen.getByRole('button', { name: 'Discard draft' }));
  expect(onBack).toHaveBeenCalledOnce();
});

/** Opens the report-a-service form, whose page URL drives the screenshot site check. */
async function openReportService(user: UserEvent, pageUrl: string): Promise<FakeApi> {
  const api = fakeApi()
    .on('POST', '/services/match', { data: matchNone })
    .on('POST', '/uploads/evidence', { json: upload })
    .on('POST', '/submissions', { status: 201, json: { id: 'receipt' } })
    .install();
  await openPanel(pageUrl);
  await user.click(await screen.findByRole('button', { name: 'Report a Service' }, { timeout: 3000 }));
  await screen.findByRole('heading', { name: 'Report a Service' });
  return api;
}

// Screenshots come from generated bytes, never a real capture.
describe('the screenshot list', () => {
  it('lists a screenshot and drops it when it is removed', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    await openReportService(user, 'https://shots.example/download');

    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByAltText('Evidence #1');
    expect(screen.getByRole('button', { name: 'Add another screenshot' })).toBeDefined();

    await user.click(screen.getByRole('button', { name: 'Remove evidence #1' }));
    expect(screen.queryByAltText('Evidence #1')).toBeNull();
    expect(screen.getByRole('button', { name: 'Add screenshot' })).toBeDefined();
  });

  it('frees the previews that a restored draft no longer holds', () => {
    const revoke = vi.fn();
    URL.revokeObjectURL = revoke;
    const { result } = renderHook(() => useScreenshotLists('https://restore.example/download'));
    const shot = (id: string): PendingEvidence => ({
      id,
      blob: new Blob([new Uint8Array([1, 2, 3])], { type: 'image/jpeg' }),
      previewUrl: `blob:${id}`,
      filename: `${id}.jpg`,
    });
    const held = shot('1700000000000-held');
    const kept = shot('1700000000001-kept');

    act(() => result.current.restore({ form: [held, kept] }));
    act(() => result.current.restore({ form: [kept] }));

    expect(revoke).toHaveBeenCalledWith('blob:1700000000000-held');
    expect(revoke).not.toHaveBeenCalledWith('blob:1700000000001-kept');
    expect(result.current.list('form').items.map((item) => item.id)).toEqual(['1700000000001-kept']);
  });

  it('uploads once and reuses that upload when a send is refused', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    let sends = 0;
    const api = fakeApi()
      .on('POST', '/services/match', { data: matchNone })
      .on('POST', '/uploads/evidence', { json: upload })
      .on('POST', '/submissions', () => {
        sends += 1;
        return sends === 1
          ? { status: 422, json: { error: 'INVALID', message: 'Needs a description' } }
          : { status: 201, json: { id: 'receipt' } };
      })
      .install();
    await openPanel('https://retry.example/download');
    await user.click(await screen.findByRole('button', { name: 'Report a Service' }, { timeout: 3000 }));
    await screen.findByRole('heading', { name: 'Report a Service' });

    await user.type(screen.getByRole('textbox', { name: 'Service name' }), 'Blocked Service');
    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByAltText('Evidence #1');
    // Capturing opens the editor. Close it without changes.
    await closeEditorWindows();

    await user.click(screen.getByRole('button', { name: 'Submit Report' }));
    await screen.findByText('Needs a description');
    expect(api.callsTo('POST', '/uploads/evidence')).toHaveLength(1);
    expect(api.callsTo('POST', '/submissions')).toHaveLength(1);

    await user.click(screen.getByRole('button', { name: 'Submit Report' }));
    await screen.findByRole('heading', { name: 'Report received' });
    expect(api.callsTo('POST', '/uploads/evidence')).toHaveLength(1);
    expect(api.callsTo('POST', '/submissions').at(1)?.json).toMatchObject({
      evidenceUrls: [upload.file.url],
    });
  });

  it('shows an upload that answers without a file address, and can be sent again', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    let uploads = 0;
    const api = fakeApi()
      .on('POST', '/services/match', { data: matchNone })
      .on('POST', '/uploads/evidence', () => {
        uploads += 1;
        return uploads === 1 ? { json: null } : { json: upload };
      })
      .on('POST', '/submissions', { status: 201, json: { id: 'receipt' } })
      .install();
    await openPanel('https://empty-upload.example/download');
    await user.click(await screen.findByRole('button', { name: 'Report a Service' }, { timeout: 3000 }));
    await screen.findByRole('heading', { name: 'Report a Service' });
    await user.type(screen.getByRole('textbox', { name: 'Service name' }), 'Blocked Service');
    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByAltText('Evidence #1');
    await closeEditorWindows();

    await user.click(screen.getByRole('button', { name: 'Submit Report' }));
    expect((await screen.findByRole('alert')).textContent).toBe(
      'A screenshot could not be uploaded: The upload answered without a file address.',
    );
    // The form is not left busy, and nothing was submitted.
    const send = screen.getByRole<HTMLButtonElement>('button', { name: 'Submit Report' });
    expect(send.disabled).toBe(false);
    expect(api.callsTo('POST', '/submissions')).toHaveLength(0);

    await user.click(send);
    await screen.findByRole('heading', { name: 'Report received' });
    expect(api.callsTo('POST', '/uploads/evidence')).toHaveLength(2);
    expect(api.callsTo('POST', '/submissions').at(0)?.json).toMatchObject({ evidenceUrls: [upload.file.url] });
  });

  it('holds back a screenshot taken on another site until it is pressed again', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    await openReportService(user, 'https://forms.example/download');

    // Switching tabs is how a capture ends up on the wrong site.
    await Promise.resolve(fakeBrowser.tabs.create({ url: 'https://elsewhere.example/report', active: true }));
    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByText(/This tab shows elsewhere\.example, not forms\.example/);
    expect(screen.queryByAltText('Evidence #1')).toBeNull();

    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByAltText('Evidence #1');
  });
});

it('keeps editing when the discard question is dismissed with Escape', async () => {
  const user = userEvent.setup();
  const onBack = vi.fn();
  render(
    <FormShell backLabel="Back" onBack={onBack} title="Report" intro="Describe the issue.">
      <input aria-label="Description" />
    </FormShell>,
  );
  await user.type(screen.getByRole('textbox', { name: 'Description' }), 'Unsent report');
  await user.click(screen.getByRole('button', { name: 'Back' }));
  fireEvent(screen.getByRole('dialog', { name: 'Discard this draft?' }), new Event('cancel'));
  expect(screen.queryByRole('dialog')).toBeNull();
  expect(onBack).not.toHaveBeenCalled();
  expect(screen.getByRole('textbox', { name: 'Description' })).toHaveProperty('value', 'Unsent report');
});

describe('the email check', () => {
  it.each(['', '   ', 'a@b.co', ' tester@example.com ', `${'a'.repeat(242)}@example.com`])('accepts %j', (value) =>
    expect(emailError(value)).toBeNull(),
  );

  it.each(['no-at', 'a@b', 'a b@c.com', 'a@b c.com', 'a@@b.co', `${'a'.repeat(243)}@example.com`])(
    'refuses %j before anything is uploaded',
    (value) => expect(emailError(value)).toBe('Enter a valid email address, or leave it blank.'),
  );
});

describe('the remembered email', () => {
  it('fills in the saved email, and follows a later save', async () => {
    await Promise.resolve(fakeBrowser.reset());
    vi.stubGlobal('chrome', fakeBrowser);
    await saveEmail('stored@example.com');
    const { result } = renderHook(() => useSavedEmail());
    await waitFor(() => expect(result.current[0]).toBe('stored@example.com'));
    await saveEmail('later@example.com');
    await waitFor(() => expect(result.current[0]).toBe('later@example.com'));
  });

  it('does not overwrite what was typed before storage answered', async () => {
    await Promise.resolve(fakeBrowser.reset());
    vi.stubGlobal('chrome', fakeBrowser);
    await saveEmail('stored@example.com');
    const { result } = renderHook(() => useSavedEmail());
    // Storage has not answered yet: typing now must win over what it will say.
    act(() => result.current[1]('typed@example.com'));
    await act(async () => {
      await new Promise((resolve) => setImmediate(resolve));
    });
    expect(result.current[0]).toBe('typed@example.com');
  });
});

/** A screenshot list on a fresh fake browser whose capture waits for the test. */
async function pendingCapture() {
  stubScreenshot();
  await Promise.resolve(fakeBrowser.reset());
  vi.stubGlobal('chrome', fakeBrowser);
  const created = await fakeBrowser.windows.create({ focused: true });
  await fakeBrowser.tabs.create({ url: 'https://slow.example/', active: true, windowId: created?.id });
  let release: (dataUrl: string) => void = () => undefined;
  let started: () => void = () => undefined;
  const capturing = new Promise<void>((resolve) => {
    started = resolve;
  });
  fakeBrowser.tabs.captureVisibleTab = () =>
    new Promise<string>((resolve) => {
      release = resolve;
      started();
    });
  const hook = renderHook(() => useScreenshotLists('https://slow.example/'));
  return {
    ...hook,
    list: () => hook.result.current.list('form'),
    /** Resolves once the browser has been asked for the capture. */
    capturing,
    release: () => release('data:image/jpeg;base64,aGVsbG8='),
  };
}

describe('capturing', () => {
  it('says why a capture failed and lets the form go on', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    await openReportService(user, 'https://denied.example/download');
    fakeBrowser.tabs.captureVisibleTab = () => Promise.reject(new Error('Permission denied'));

    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByText('Could not take a screenshot: Permission denied');
    expect(screen.queryByAltText('Evidence #1')).toBeNull();
    expect(screen.getByRole<HTMLButtonElement>('button', { name: 'Add screenshot' }).disabled).toBe(false);
  });

  it('calls a tab with no address another page', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    await openReportService(user, 'https://forms.example/download');
    await Promise.resolve(fakeBrowser.tabs.create({ active: true }));

    await user.click(screen.getByRole('button', { name: 'Add screenshot' }));
    await screen.findByText(/This tab shows another page, not forms\.example/);
  });

  it('takes one capture at a time', async () => {
    const { list, release } = await pendingCapture();
    let first: Promise<PendingEvidence | null> = Promise.resolve(null);
    let second: PendingEvidence | null = null;
    await act(async () => {
      first = list().take();
      second = await list().take();
    });
    expect(second).toBeNull();
    await act(async () => {
      release();
      expect(await first).not.toBeNull();
    });
    expect(list().items).toHaveLength(1);
  });

  it('drops a capture that finishes after the form has closed', async () => {
    const { list, release, capturing, unmount } = await pendingCapture();
    const revoke = vi.fn();
    URL.revokeObjectURL = revoke;
    let taken: Promise<PendingEvidence | null> = Promise.resolve(null);
    act(() => {
      taken = list().take();
    });
    await capturing;
    unmount();
    release();
    expect(await taken).toBeNull();
    expect(revoke).toHaveBeenCalledWith('blob:fake-evidence');
  });
});

describe('picking files instead of capturing', () => {
  it('offers an upload beside the camera, for the image types the API takes', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    await openReportService(user, 'https://upload.example/download');

    expect(screen.getByRole('button', { name: 'Upload images' })).toBeDefined();
    expect(screen.getByText('Or drop an image here.')).toBeDefined();
    const input = document.querySelector<HTMLInputElement>('input[type="file"]');
    if (input === null) throw new Error('The form has no file picker');
    expect(input.getAttribute('accept')).toBe('image/jpeg,image/png,image/gif,image/webp');
    expect(input.hasAttribute('multiple')).toBe(true);
  });

  it('takes an image dropped on the field, and opens it for editing', async () => {
    const user = userEvent.setup();
    stubScreenshot();
    await openReportService(user, 'https://drop.example/download');

    const field = screen.getByText('Or drop an image here.').closest('div');
    if (field === null) throw new Error('The screenshot field is not there');
    const file = new File(['png-bytes'], 'dropped.png', { type: 'image/png' });
    fireEvent.drop(field, { dataTransfer: { types: ['Files'], files: [file] } });

    await screen.findByAltText('Evidence #1');
    await closeEditorWindows();
    expect(screen.getByRole('button', { name: 'Add another screenshot' })).toBeDefined();
  });
});

/** A screenshot list on its own, for reading what an added file became. */
function fileList() {
  URL.createObjectURL = () => 'blob:picked';
  return renderHook(() => useScreenshotLists('https://files.example/download'));
}

describe('adding a file to the list', () => {
  it('keeps the bytes, the type and the name the file already had', () => {
    const { result } = fileList();
    const file = new File(['png-bytes'], 'evidence.png', { type: 'image/png' });
    let added: PendingEvidence[] = [];
    act(() => {
      added = result.current.list('form').add([file], 10);
    });
    expect(added).toHaveLength(1);
    expect(added[0]?.filename).toBe('evidence.png');
    expect(added[0]?.blob.type).toBe('image/png');
    expect(result.current.list('form').items).toHaveLength(1);
    expect(result.current.list('form').error).toBeNull();
  });

  it.each([
    ['text/plain', 'notes.txt', 'That file is not a JPEG, PNG, GIF or WebP image.'],
    ['image/svg+xml', 'logo.svg', 'That file is not a JPEG, PNG, GIF or WebP image.'],
    ['image/png', 'huge.png', 'That image is larger than 5 MiB. Pick a smaller one.'],
  ])('refuses %s with a message, and adds nothing', (type, name, message) => {
    const { result } = fileList();
    const bytes = type === 'image/png' ? new Uint8Array(5 * 1024 * 1024 + 1) : 'x';
    const file = new File([bytes], name, { type });
    let added: PendingEvidence[] = [];
    act(() => {
      added = result.current.list('form').add([file], 10);
    });
    expect(added).toHaveLength(0);
    expect(result.current.list('form').items).toHaveLength(0);
    expect(result.current.list('form').error).toBe(message);
  });

  it('adds only what there is room for, and says so', () => {
    const { result } = fileList();
    const shot = (name: string) => new File(['x'], name, { type: 'image/png' });
    let added: PendingEvidence[] = [];
    act(() => {
      added = result.current.list('form').add([shot('one.png'), shot('two.png')], 1);
    });
    expect(added).toHaveLength(1);
    expect(result.current.list('form').items).toHaveLength(1);
    expect(result.current.list('form').error).toBe(
      'This form already holds the most screenshots. Remove one to add another.',
    );
  });
});
